# Generated by Django 5.0.3 on 2024-03-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksapimodel',
            name='isbc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
